In [38]:
import numpy as np
import pandas as pd
import datetime as dt
import calendar as cal

# Load the stock master file

In [39]:
df_stocks = pd.read_csv('../dataset/KLSE_investing.csv', index_col=['name'])
df_stocks.head(10)

,link,last,high,low,change,change_percent,volume
name,,,,,,,
Priceworth International,https://www.investing.com/equities/priceworth-...,0.045,0.055,0.045,-0.005,-10.00%,223.12M
Sapura Energy,https://www.investing.com/equities/sapurakenca...,0.335,0.345,0.335,0.000,0.00%,53.62M
Borneo Oil,https://www.investing.com/equities/borneo-oil-bhd,0.055,0.060,0.055,0.000,0.00%,50.93M
MY EG Services,https://www.investing.com/equities/my-eg-servi...,1.630,1.700,1.620,-0.020,-1.21%,35.62M
Tiger Synergy Bhd,https://www.investing.com/equities/tiger-syner...,0.070,0.075,0.065,-0.005,-6.67%,29.80M
Nova MSC,https://www.investing.com/equities/nova-msc-bhd,0.160,0.160,0.145,0.005,+3.23%,22.05M
Frontken Corp,https://www.investing.com/equities/frontken-co...,0.920,0.960,0.915,0.000,0.00%,20.90M
Globaltec Formation,https://www.investing.com/equities/globaltec-f...,0.040,0.045,0.035,-0.005,-11.11%,19.77M
AirAsia X,https://www.investing.com/equities/airasia-x-bhd,0.290,0.305,0.290,-0.010,-3.33%,19.08M
Nexgram,https://www.investing.com/equities/nexgram-hol...,0.025,0.025,0.020,0.000,0.00%,15.68M

# Load dividends file

In [55]:
df_dividends = pd.read_csv('../dataset/KLSE_dividends_investing.csv', dtype='str')
df_dividends.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2315 entries, 0 to 2314
Data columns (total 6 columns):
code                2315 non-null object
name                2315 non-null object
ex_dividend_date    2315 non-null object
dividend            2315 non-null object
payment_date        2315 non-null object
yield               2315 non-null object
dtypes: object(6)
memory usage: 108.6+ KB

In [56]:
df_dividends.describe()

,code,name,ex_dividend_date,dividend,payment_date,yield
count,2315,2315,2315,2315,2315,2315
unique,585,585,761,429,747,710
top,7237,Genting Plantations Bhd (GENP),"Jun 28, 2017",0.02,"Jun 30, 2017",-
freq,6,6,30,136,21,61

In [57]:
df_dividends.columns

Index(['code', 'name', 'ex_dividend_date', 'dividend', 'payment_date',
       'yield'],
      dtype='object')

# Display some data

In [58]:
df_dividends.head(10)

,code,name,ex_dividend_date,dividend,payment_date,yield
0,5218,Sapura Energy Bhd (SAEN),"Apr 12, 2017",0.01,"Apr 28, 2017",2.94%
1,5218,Sapura Energy Bhd (SAEN),"Jul 29, 2015",0.0135,"Aug 28, 2015",0.72%
2,138,MY EG Services Bhd (MYEG),"Apr 24, 2018",0.017,"May 25, 2018",1.30%
3,138,MY EG Services Bhd (MYEG),"Jan 04, 2018",0.017,"Feb 06, 2018",0.63%
4,138,MY EG Services Bhd (MYEG),"Apr 21, 2017",0.0137,"May 24, 2017",0.64%
5,138,MY EG Services Bhd (MYEG),"Dec 23, 2016",0.012,"Jan 25, 2017",0.74%
6,138,MY EG Services Bhd (MYEG),"Apr 22, 2016",0.012,"May 24, 2016",0.56%
7,138,MY EG Services Bhd (MYEG),"Jan 04, 2016",0.0095,"Feb 04, 2016",0.44%
8,128,Frontken Corporation Bhd (FRKN),"Sep 15, 2017",0.005,"Oct 04, 2017",0.60%
9,9385,Lay Hong Bhd (LAYH),"Oct 18, 2018",0.005,"Nov 15, 2018",0.79%

## Create the year column

In [60]:
df_dividends['dividend_year'] = df_dividends['ex_dividend_date']
df_dividends.head(10)

,code,name,ex_dividend_date,dividend,payment_date,yield,dividend_year
0,5218,Sapura Energy Bhd (SAEN),"Apr 12, 2017",0.01,"Apr 28, 2017",2.94%,"Apr 12, 2017"
1,5218,Sapura Energy Bhd (SAEN),"Jul 29, 2015",0.0135,"Aug 28, 2015",0.72%,"Jul 29, 2015"
2,138,MY EG Services Bhd (MYEG),"Apr 24, 2018",0.017,"May 25, 2018",1.30%,"Apr 24, 2018"
3,138,MY EG Services Bhd (MYEG),"Jan 04, 2018",0.017,"Feb 06, 2018",0.63%,"Jan 04, 2018"
4,138,MY EG Services Bhd (MYEG),"Apr 21, 2017",0.0137,"May 24, 2017",0.64%,"Apr 21, 2017"
5,138,MY EG Services Bhd (MYEG),"Dec 23, 2016",0.012,"Jan 25, 2017",0.74%,"Dec 23, 2016"
6,138,MY EG Services Bhd (MYEG),"Apr 22, 2016",0.012,"May 24, 2016",0.56%,"Apr 22, 2016"
7,138,MY EG Services Bhd (MYEG),"Jan 04, 2016",0.0095,"Feb 04, 2016",0.44%,"Jan 04, 2016"
8,128,Frontken Corporation Bhd (FRKN),"Sep 15, 2017",0.005,"Oct 04, 2017",0.60%,"Sep 15, 2017"
9,9385,Lay Hong Bhd (LAYH),"Oct 18, 2018",0.005,"Nov 15, 2018",0.79%,"Oct 18, 2018"